### ISSUE TITLE
Question: Why does it not support upload stream bandwidth?

### ISSUE THREAD

**Issue by kapilsukhyani** [facebook/network-connection-class#19]

**Comment by SeyelentEco** [comment]
Since we're measuring the current connection class by monitoring traffic in your app we need a decent amount of traffic before we can get a good sense for how fast your current connection is.  Since uploads are few and far between in most apps, we just haven't found a need to add this functionality.  If you need it for your application, it should be pretty trivial to add in the same way we've measured and calculated the apps current downstream bandwidth.

**Comment by kapilsukhyani** [comment]
Thanks, make sense.

**Comment by pranay18** [comment]
@SeyelentEco can you please elaborate a little bit more on how to get this library working for monitoring uploads as well?
