### ISSUE TITLE
Calculate upload speed

### ISSUE THREAD

**Issue by jalpesh** [facebook/network-connection-class#5]
I could not figure out how to calculate the upload speed, Is there any way this is possible?

**Comment by SeyelentEco** [comment]
You can modify the QTagParser class to parse the tx_bytes too.  https://github.com/facebook/network-connection-class/blob/master/connectionclass/src/main/java/com/facebook/network/connectionclass/QTagParser.java#L65

We don't record / calculate the upload speed because there usually aren't enough large uploads to be able to get a reliable measurement.  It could be added pretty easily if your app has that requirement but most apps don't upload enough data to get a measurement we could rely on.

**Comment by jalpesh** [comment]
Thank you SeyelentEco..
